modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory

authors="Shadows_of_Fire" #optional

[[mods]] #mandatory

modId="toastcontrol" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Toast Control" #mandatory

description='''
Blocking annoying popups since 1.12
'''

[[dependencies.toastcontrol]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.0.45,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.toastcontrol]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.toastcontrol]]
    modId="placebo"
    mandatory=true
    versionRange="[2.1.4,)"
    ordering="NONE"
    side="BOTH"